services:
  postgres:
    image: postgres:16-alpine
    container_name: code-rank-senai-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  judge0-server:
    image: judge0/judge0:1.13.1
    container_name: judge0-server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-workers:
    image: judge0/judge0:1.13.1
    container_name: judge0-workers
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:16-alpine
    container_name: judge0-db
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0password
    volumes:
      - judge0-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  judge0-redis:
    image: redis:7.2-alpine
    container_name: judge0-redis
    restart: unless-stopped

volumes:
  pgdata:
  judge0-pgdata:
